export type Priority = 'low' | 'medium' | 'high' | 'panic';

export interface TaskStep {
  id: string;
  text: string;
  isCompleted: boolean;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  deadline: string; // ISO String or YYYY-MM-DD
  priority: Priority;
  duration: number; // in minutes
  tags: string[];
  isCompleted: boolean;
  scheduledSlot?: string; // e.g. "Monday 09:00"
  executionSteps?: TaskStep[]; // Generated by Gemini
  executionDrafts?: {
    title: string;
    content: string;
  }[]; // Generated by Gemini
  panicScore?: number; // Calculated score of urgency (0 to 100)
}

export interface Goal {
  id: string;
  title: string;
  deadline: string;
  progress: number; // 0 to 100
  target: string;
  isCompleted: boolean;
}

export interface Habit {
  id: string;
  name: string;
  streak: number;
  lastCompleted?: string; // YYYY-MM-DD
  history: string[]; // List of completed dates (YYYY-MM-DD)
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'assistant';
  text: string;
  timestamp: string;
}

export interface ScheduleSlot {
  id: string;
  day: string; // "Monday", "Tuesday", etc.
  time: string; // "09:00", "10:00", etc.
  taskId: string | null;
  label?: string; // custom title if not a linked task
}

export interface DynamicRecommendations {
  summary: string;
  advice: string[];
  suggestedFocusId: string | null;
}
